### ISSUE TITLE
Update Minimal Mistakes theme

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/citation-style-language.github.io#21]
I'm getting a lot of warnings like

```
DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("variable-exists")) instead.
```

when I build the site locally. See https://github.com/mmistakes/minimal-mistakes/issues/1114.

@pmelchor, if you have time in December, it might future-proof the site a bit more if you could bring this repo up-to-date with upstream theme changes from the minimal-mistakes repo. (I always found this the hardest part of using a theme like Minimal Mistakes on GitHub Pages)

**Comment by pmelchor** [comment]
Sure, I will look into that and see if any code needs moving around to make updates easier.

**Comment by rmzelle** [comment]
@pmelchor, it's now possible to simply select GitHub-hosted third-party themes with GitHub Pages (this includes Minimal Mistakes): https://github.com/blog/2464-use-any-theme-with-github-pages

I don't know if this makes things simpler or more complicated, but worth keeping an eye on. (it depends on https://github.com/benbalter/jekyll-remote-theme)

**Comment by rmzelle** [comment]
(If it's not possible to fix the remote theme to a certain version, we could perhaps also fork the Minimal Mistake repo and use our fork of the theme as a remote theme. That would allow us to separate the theme and content into separate repos. Again, not sure that would make things simpler.)

**Comment by pmelchor** [comment]
Perfect, I'll look into it.

**Comment by pmelchor** [comment]
@rmzelle I have been looking into this. We have three options:

**1. Use https://github.com/mmistakes/minimal-mistakes as remote theme**.
- Pros: clear separation of theme and cut; instant theme upgrades.
- Cons: not all customizations are possible; we may be affected by uncontrolled breaking changes; we may not like the direction the theme takes.

**2. Fork Minimal Mistakes and use the fork as remote** (as you suggested)
- Pros: clear separation of theme and customisations; easy and controlled theme upgrades.
- Cons: not all customizations are possible; we may not like the direction the theme takes.

**3. Apply theme upgrades manually**
- Pros: full customization; we can be selective about which changes to apply.
- Cons: manual, more complex upgrades.

If you ask me, I would go with (3):
- It is more time consuming but it allows us to have a CSL theme based on MM rather than a slightly customized MM theme.
- And theme upgrades tend to be nice-to-haves rather than musts.

I am currently trying (3) locally and it seems like it is not a big issue.

What do you think?

**Comment by adam3smith** [comment]
based on my experience with Jekyll, though without having looked at the issue here, I'd agree with 3

**Comment by pmelchor** [comment]
I may have lied about "not all customizations being possible" in 1 and 2. I am going to give 2 a try as well and I will let you know how that goes.

**Comment by pmelchor** [comment]
OK, 2 could work but I do not like the fact that deploys would need to be synchronized: things can break if you update the customizaton repo and the theme-fork repo at different times. I think a single repo that can be easily tested locally in full (thus option 3) is a better and safer model.

**Comment by rmzelle** [comment]
Sure, we can do (3). Could you see if you can manage to update our current fork, and document any tricky parts in the process for us?

**Comment by pmelchor** [comment]
> Could you see if you can manage to update our current fork, and document any tricky parts for us?

Yes, that's what I'm up to right now :-)

**Comment by pmelchor** [comment]
Basic documentation on upgrading the theme:
https://github.com/citation-style-language/citation-style-language.github.io/wiki/Upgrading-the-Minimal-Mistakes-theme

**Comment by rmzelle** [comment]
> Basic documentation on upgrading the theme:
> https://github.com/citation-style-language/citation-style-language.github.io/wiki/Upgrading-the-Minimal-Mistakes-theme

Thanks! That's easier than I imagined (at least regarding the use of Git). I assumed you'd be merging the upstream commits, but this works just as well. Hope the manual conflict resolution didn't take too much time!

**Comment by pmelchor** [comment]
I did try the Git route, but I found it not to be worth it. In other projects based on Wordpress we use the download and merge process and it works just fine.

There were some structural changes to the theme that took me a while to understand, but no big issues in the end :-)
